---

- name: Install console fonts
  dnf:
    name: terminus-fonts-console
    state: present
  become: yes

- name: Set console font
  lineinfile:
    path: /etc/vconsole.conf
    regexp: "^FONT="
    line: FONT="ter-v32b"
    state: present
  become: yes

