---

- name: Add Flathub repo
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  loop: "{{ laptop_flatpaks }}"
