---

- name: Disable wifi when ethernet is in use
  copy:
    src: 99-wlan
    dest: /etc/NetworkManager/dispatcher.d/99-wlan
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: restart_networkmanager

- name: Enable the DNSmasq plugin in NetworkManager
  copy:
    src: main.conf
    dest: /etc/NetworkManager/conf.d/main.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart_networkmanager
