---
# handlers file for common

- name: generate_grub_config
  command: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  become: yes

- name: restart_networkmanager
  service:
    name: NetworkManager
    state: restarted
  become: yes

