---

- hosts: localhost
  vars_files:
    - "../vars/work.yml"
  roles:
    - role: common
      tags: [common]

    - role: jaredhocutt.oh_my_zsh
      tags: [oh_my_zsh]

- hosts: localhost
  vars_files:
    - "../vars/work.yml"
  roles:
    - role: jaredhocutt.azure_cli
      tags: [azure_cli]

    - role: jaredhocutt.brave_browser
      tags: [brave_browser]

    - role: jaredhocutt.dconf_settings
      tags: [dconf_settings]

    - role: jaredhocutt.dotfiles
      tags: [dotfiles]

    - role: jaredhocutt.insync
      tags: [insync]

    - role: jaredhocutt.ferdi
      tags: [ferdi]

    - role: jaredhocutt.gitkraken
      tags: [gitkraken]

    - role: jaredhocutt.gnome_extensions
      tags: [gnome_extensions]

    - role: jaredhocutt.handbrake
      tags: [handbrake]

    # - role: jaredhocutt.kdenlive
    #   tags: [kdenlive]

    # - role: jaredhocutt.obs_studio
    #   tags: [obs_studio]

    - role: jaredhocutt.redhat_vpn
      tags: [redhat_vpn]

    - role: jaredhocutt.restic
      tags: [restic]

    - role: jaredhocutt.vlc
      tags: [vlc]

    - role: jaredhocutt.vscode
      tags: [vscode]
